_target_: 'diffusion_policy.env_runner.robomimic_image_runner.AdversarialRobomimicImageRunnerIBC'
checkpoint: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_1/checkpoints/epoch=3050-test_mean_score=0.773.ckpt'
task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'ibc'
n_envs: 28
log: True
device: 'cuda:0'
attack: True
attack_type: 'fgsm'
epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
clip_min: 0
clip_max: 1
view: 'both'

# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int:
