_target_: 'diffusion_policy.env_runner.robomimic_image_runner.RobomimicImageRunner'
checkpoints: 
    train0: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/vanilla_bc/train_0/checkpoints/epoch=0500-test_mean_score=1.000.ckpt'
    train1: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/vanilla_bc/train_1/checkpoints/epoch=0100-test_mean_score=1.000.ckpt'
    train2: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/vanilla_bc/train_2/checkpoints/epoch=0100-test_mean_score=1.000.ckpt'
checkpoint: ${checkpoints.train0}

task: 'lift_ph'
dataset_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/robomimic/datasets/lift/ph/image.hdf5'
algo: 'bc'
n_envs: 22
n_test: 20
n_train: 2
log: True
device: 'cuda:0'
attack: True
##### ********** IF CHANGING ATTACK TYPE, CHECK THE TARGET FUNCTION ********** #####
attack_type: 'patch'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/vanilla_bc/train_0/checkpoints/untar_pert_0.0625_epoch_20_mean_score_0.5714285714285714_robot0_eye_in_hand_image_ild.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/vanilla_bc/train_0/checkpoints/untar_pert_0.0625_epoch_15_mean_score_0.62_robot0_eye_in_hand_image.pkl'

# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/vanilla_bc/train_0/checkpoints/untar_pert_0.0625_epoch_90_mean_score_0.35714285714285715_robot0_eye_in_hand_image_ild.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_0/checkpoints/untar_pert_0.0625_epoch_5_mean_score_0.0_robot0_eye_in_hand_image.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/lstm_gmm/train_0/checkpoints/untar_pert_0.0625_epoch_5_mean_score_0.0_robot0_eye_in_hand_image.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/ibc_dfo/train_0/checkpoints/untar_pert_0.0625_epoch_10_mean_score_0.82_robot0_eye_in_hand_image.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/data/experiments/image/lift_ph/bet/train6/checkpoints/tar_pert_0.0625_epoch_50_mean_score_0.07142857142857142_robot0_eye_in_hand_image_orig_obs.pkl'
# patch_path: '/teamspace/studios/this_studio/bc_attacks/diffusion_policy/random_patch.pkl'
targeted: False
# epsilons: [0.01, 0.03, 0.1, 0.3, 0.5]
# epsilons: [0.01953125, 0.03125, 0.0625, 0.125]
epsilon: 0.0625
eps_iter: 0.0625
perturbations: [0.15, 0.15, 0., 0., 0., 0., 0]
clip_min: 0
clip_max: 1
view: 'robot0_eye_in_hand_image'
rand_int: False
action_space: None
rand_target: False
n_iter: 40
norm: 'linf'
max_steps: 400
patch_size: 16
seed: 1023
save_video: False
n_vis: 3

# pgd:
#  eta_bound:
#  num_iter:
#  norm:
#  rand_int:

